/**
 * profile.js — Profile import / export
 * Schema: { name, template, logo, marquee, spine, cover }
 * Each region: { x, y, width, height }
 */

export const SCHEMA_VERSION = "1.0.0";

/** Default empty profile */
export function emptyProfile(name = "untitled") {
  return {
    name,
    version: SCHEMA_VERSION,
    template: "template.png",
    spine_source_frac: 0.20,
    spine_source: "left",
    cover_fit: "stretch",
    spine_layout: {
      logo_alpha: 0.85,
      rotate_logos: true,
      game:   { max_w: 80,  max_h: 320, center_y: 453 },
      top:    { max_w: 80,  max_h: 120, center_y: 150 },
      bottom: { max_w: 80,  max_h: 80,  center_y: 780 }
    },
    template_size: { width: 700, height: 1000 },
    spine: { width: 100, height: 877 },
    cover: { width: 536, height: 880 },
    spine_quad: { tl:[0,58], tr:[100,96], br:[100,998], bl:[0,935] },
    cover_quad: { tl:[100,96], tr:[636,44], br:[636,918], bl:[100,998] },
  };
}

/**
 * Convert the canvas object list to the JSON profile schema.
 * @param {string} name
 * @param {object[]} objects  — layout rectangles from canvas
 * @param {HTMLImageElement|null} templateImg
 */
export function exportProfile(name, objects, templateImg, extras = {}) {
  const find = (type) => objects.find(o => o.type === type);
  const toRect = (o) => o ? { x: Math.round(o.x), y: Math.round(o.y), width: Math.round(o.w), height: Math.round(o.h) } : { x:0, y:0, width:0, height:0 };

  const spine  = find("spine");
  const cover  = find("cover");
  const tw = templateImg ? templateImg.naturalWidth  : (extras.tw || 700);
  const th = templateImg ? templateImg.naturalHeight : (extras.th || 1000);

  // Derive quad corners from the spine/cover bounding boxes
  // (Simplified: assumes rectangular placement — designer can refine)
  const spineRect = toRect(spine);
  const coverRect = toRect(cover);

  const makeQuad = (r) => ({
    tl: [r.x,        r.y],
    tr: [r.x+r.width, r.y],
    br: [r.x+r.width, r.y+r.height],
    bl: [r.x,        r.y+r.height],
  });

  return {
    name,
    version: SCHEMA_VERSION,
    template: "template.png",
    template_size: { width: tw, height: th },
    spine: { width: spineRect.width,  height: spineRect.height },
    cover: { width: coverRect.width,  height: coverRect.height },
    spine_quad: makeQuad(spineRect),
    cover_quad: makeQuad(coverRect),
    spine_source_frac: extras.spine_source_frac ?? 0.20,
    spine_source: extras.spine_source ?? "left",
    cover_fit:    extras.cover_fit ?? "stretch",
    spine_layout: extras.spine_layout ?? {
      logo_alpha: 0.85, rotate_logos: true,
      game:   { max_w: 80,  max_h: 320, center_y: Math.round(th * 0.5) },
      top:    { max_w: 80,  max_h: 120, center_y: Math.round(th * 0.16) },
      bottom: { max_w: 80,  max_h: 80,  center_y: Math.round(th * 0.84) }
    },
    logo:    toRect(find("logo")),
    marquee: toRect(find("marquee")),
  };
}

/** Load a profile JSON and return canvas objects + extras. */
export function importProfile(json) {
  const objects = [];

  const addRect = (type, r) => {
    if (!r) return;
    objects.push({ type, x: r.x ?? 0, y: r.y ?? 0, w: r.width ?? 0, h: r.height ?? 0 });
  };

  // Derive spine rect from spine_quad if available
  if (json.spine_quad) {
    const q = json.spine_quad;
    const xs = [q.tl[0], q.tr[0], q.br[0], q.bl[0]];
    const ys = [q.tl[1], q.tr[1], q.br[1], q.bl[1]];
    addRect("spine", { x: Math.min(...xs), y: Math.min(...ys), width: Math.max(...xs) - Math.min(...xs), height: Math.max(...ys) - Math.min(...ys) });
  }

  if (json.cover_quad) {
    const q = json.cover_quad;
    const xs = [q.tl[0], q.tr[0], q.br[0], q.bl[0]];
    const ys = [q.tl[1], q.tr[1], q.br[1], q.bl[1]];
    addRect("cover", { x: Math.min(...xs), y: Math.min(...ys), width: Math.max(...xs) - Math.min(...xs), height: Math.max(...ys) - Math.min(...ys) });
  }

  addRect("logo",    json.logo);
  addRect("marquee", json.marquee);

  return { objects, extras: json, templateName: json.template };
}

/** Generate a Python snippet compatible with box3d core. */
export function exportPython(profile) {
  const j = JSON.stringify(profile, null, 2);
  return `# Auto-generated by Box3D Designer Pro v${SCHEMA_VERSION}
# Paste into your box3d profiles/ directory as profiles/${profile.name}/profile.json

PROFILE = ${j.replace(/"([^"]+)":/g, '$1:').replace(/"/g, "'")}
`;
}

/** Download a file to the user's machine. */
export function downloadFile(content, filename, mime = "application/json") {
  const blob = new Blob([content], { type: mime });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click();
  document.body.removeChild(a); URL.revokeObjectURL(url);
}
